// todo: remove mock functionality - this file contains all mock data for the ERP prototype

import { Attendance } from "@/components/hr/AttendanceList";
import { Movement } from "@/components/warehouse/MovementList";

export const mockCustomers = [
  {
    id: "C001",
    name: "Acme Corporation",
    email: "orders@acme.com",
    phone: "+1 555-0100",
    status: "active",
    totalOrders: 45,
    totalSpent: 125000,
  },
  {
    id: "C002",
    name: "TechStart Inc.",
    email: "purchasing@techstart.io",
    phone: "+1 555-0101",
    status: "active",
    totalOrders: 23,
    totalSpent: 67500,
  },
  {
    id: "C003",
    name: "Global Supplies Ltd",
    email: "procurement@globalsupplies.com",
    phone: "+1 555-0102",
    status: "active",
    totalOrders: 89,
    totalSpent: 234000,
  },
  {
    id: "C004",
    name: "Metro Retail Group",
    email: "buying@metroretail.com",
    phone: "+1 555-0103",
    status: "inactive",
    totalOrders: 12,
    totalSpent: 28900,
  },
  {
    id: "C005",
    name: "Summit Industries",
    email: "orders@summitind.com",
    phone: "+1 555-0104",
    status: "active",
    totalOrders: 67,
    totalSpent: 189000,
  },
];

export const mockVendors = [
  {
    id: "V001",
    name: "Prime Suppliers Co.",
    email: "sales@primesuppliers.com",
    phone: "+1 555-0200",
    status: "active",
    activePOs: 5,
    totalValue: 45000,
  },
  {
    id: "V002",
    name: "Quality Materials Inc.",
    email: "orders@qualitymaterials.com",
    phone: "+1 555-0201",
    status: "active",
    activePOs: 3,
    totalValue: 32000,
  },
  {
    id: "V003",
    name: "FastShip Logistics",
    email: "partners@fastship.com",
    phone: "+1 555-0202",
    status: "active",
    activePOs: 2,
    totalValue: 18500,
  },
  {
    id: "V004",
    name: "Industrial Parts Ltd",
    email: "sales@industrialparts.co",
    phone: "+1 555-0203",
    status: "pending",
    activePOs: 0,
    totalValue: 0,
  },
];

export const mockProducts = [
  {
    id: "P001",
    sku: "WDG-001",
    name: "Industrial Widget A",
    category: "Widgets",
    uom: "EA",
    price: 49.99,
    stock: 234,
    minLevel: 50,
    maxLevel: 500,
    location: "A-01-01",
  },
  {
    id: "P002",
    sku: "WDG-002",
    name: "Industrial Widget B",
    category: "Widgets",
    uom: "EA",
    price: 79.99,
    stock: 156,
    minLevel: 30,
    maxLevel: 300,
    location: "A-01-02",
  },
  {
    id: "P003",
    sku: "CPT-001",
    name: "Component Alpha",
    category: "Components",
    uom: "EA",
    price: 24.5,
    stock: 12,
    minLevel: 100,
    maxLevel: 1000,
    location: "B-02-01",
  },
  {
    id: "P004",
    sku: "CPT-002",
    name: "Component Beta",
    category: "Components",
    uom: "BOX",
    price: 189.0,
    stock: 89,
    minLevel: 20,
    maxLevel: 200,
    location: "B-02-02",
  },
  {
    id: "P005",
    sku: "MAT-001",
    name: "Raw Material X",
    category: "Materials",
    uom: "KG",
    price: 12.75,
    stock: 2450,
    minLevel: 500,
    maxLevel: 5000,
    location: "C-03-01",
  },
  {
    id: "P006",
    sku: "ASM-001",
    name: "Assembly Kit Pro",
    category: "Assemblies",
    uom: "KIT",
    price: 349.0,
    stock: 45,
    minLevel: 10,
    maxLevel: 100,
    location: "D-01-01",
  },
];

export const mockSalesOrders = [
  {
    id: "SO-001",
    customerId: "C001",
    customerName: "Acme Corporation",
    date: "2024-12-01",
    status: "invoiced",
    total: 4599.5,
    items: 3,
  },
  {
    id: "SO-002",
    customerId: "C002",
    customerName: "TechStart Inc.",
    date: "2024-12-02",
    status: "delivered",
    total: 2340.0,
    items: 2,
  },
  {
    id: "SO-003",
    customerId: "C003",
    customerName: "Global Supplies Ltd",
    date: "2024-12-03",
    status: "confirmed",
    total: 8750.0,
    items: 5,
  },
  {
    id: "SO-004",
    customerId: "C001",
    customerName: "Acme Corporation",
    date: "2024-12-04",
    status: "draft",
    total: 1250.0,
    items: 1,
  },
  {
    id: "SO-005",
    customerId: "C005",
    customerName: "Summit Industries",
    date: "2024-12-05",
    status: "confirmed",
    total: 15600.0,
    items: 8,
  },
];

export const mockPurchaseOrders = [
  {
    id: "PO-001",
    vendorId: "V001",
    vendorName: "Prime Suppliers Co.",
    date: "2024-12-01",
    status: "received",
    total: 12500.0,
    items: 4,
  },
  {
    id: "PO-002",
    vendorId: "V002",
    vendorName: "Quality Materials Inc.",
    date: "2024-12-02",
    status: "ordered",
    total: 8900.0,
    items: 3,
  },
  {
    id: "PO-003",
    vendorId: "V001",
    vendorName: "Prime Suppliers Co.",
    date: "2024-12-03",
    status: "draft",
    total: 5600.0,
    items: 2,
  },
  {
    id: "PO-004",
    vendorId: "V003",
    vendorName: "FastShip Logistics",
    date: "2024-12-04",
    status: "ordered",
    total: 3400.0,
    items: 2,
  },
];

export const mockDeliveries = [
  {
    id: "DEL-001",
    orderId: "SO-001",
    customerName: "Acme Corporation",
    date: "2024-12-03",
    status: "shipped",
    items: 3,
  },
  {
    id: "DEL-002",
    orderId: "SO-002",
    customerName: "TechStart Inc.",
    date: "2024-12-04",
    status: "delivered",
    items: 2,
  },
  {
    id: "DEL-003",
    orderId: "SO-003",
    customerName: "Global Supplies Ltd",
    date: "2024-12-05",
    status: "picking",
    items: 5,
  },
  {
    id: "DEL-004",
    orderId: "SO-005",
    customerName: "Summit Industries",
    date: "2024-12-06",
    status: "packing",
    items: 8,
  },
];

export const mockInvoices = [
  {
    id: "INV-001",
    orderId: "SO-001",
    customerName: "Acme Corporation",
    date: "2024-12-03",
    dueDate: "2024-12-18",
    status: "paid",
    total: 4599.5,
  },
  {
    id: "INV-002",
    orderId: "SO-002",
    customerName: "TechStart Inc.",
    date: "2024-12-04",
    dueDate: "2024-12-19",
    status: "unpaid",
    total: 2340.0,
  },
  {
    id: "INV-003",
    orderId: "SO-003",
    customerName: "Global Supplies Ltd",
    date: "2024-12-05",
    dueDate: "2024-12-20",
    status: "partial",
    total: 8750.0,
    paid: 4000.0,
  },
];

export const mockEmployees = [
  {
    id: "E001",
    name: "Sarah Johnson",
    email: "sarah.johnson@unanza.com",
    department: "Sales",
    position: "Sales Manager",
    status: "active",
    hireDate: "2022-03-15",
  },
  {
    id: "E002",
    name: "Michael Chen",
    email: "michael.chen@unanza.com",
    department: "Warehouse",
    position: "Warehouse Supervisor",
    status: "active",
    hireDate: "2021-08-01",
  },
  {
    id: "E003",
    name: "Emily Rodriguez",
    email: "emily.rodriguez@unanza.com",
    department: "Finance",
    position: "Senior Accountant",
    status: "active",
    hireDate: "2020-01-10",
  },
  {
    id: "E004",
    name: "David Kim",
    email: "david.kim@unanza.com",
    department: "HR",
    position: "HR Coordinator",
    status: "active",
    hireDate: "2023-05-20",
  },
  {
    id: "E005",
    name: "Lisa Wang",
    email: "lisa.wang@unanza.com",
    department: "Operations",
    position: "Operations Analyst",
    status: "on-leave",
    hireDate: "2022-11-01",
  },
];

export const mockLeaveRequests = [
  {
    id: "LR-001",
    employeeId: "E001",
    employeeName: "Sarah Johnson",
    type: "vacation",
    startDate: "2024-12-20",
    endDate: "2024-12-27",
    status: "approved",
    days: 5,
  },
  {
    id: "LR-002",
    employeeId: "E003",
    employeeName: "Emily Rodriguez",
    type: "sick",
    startDate: "2024-12-10",
    endDate: "2024-12-11",
    status: "approved",
    days: 2,
  },
  {
    id: "LR-003",
    employeeId: "E002",
    employeeName: "Michael Chen",
    type: "personal",
    startDate: "2024-12-15",
    endDate: "2024-12-15",
    status: "pending",
    days: 1,
  },
  {
    id: "LR-004",
    employeeId: "E005",
    employeeName: "Lisa Wang",
    type: "vacation",
    startDate: "2024-12-01",
    endDate: "2024-12-14",
    status: "approved",
    days: 10,
  },
];

export const mockAttendance: Attendance[] = [
  {
    id: "ATT-001",
    employeeId: "E001",
    employeeName: "Sarah Johnson",
    date: "2024-12-05",
    checkIn: "08:45",
    checkOut: "17:30",
    hours: 8.75,
    status: "present",
  },
  {
    id: "ATT-002",
    employeeId: "E002",
    employeeName: "Michael Chen",
    date: "2024-12-05",
    checkIn: "07:00",
    checkOut: "15:30",
    hours: 8.5,
    status: "present",
  },
  {
    id: "ATT-003",
    employeeId: "E003",
    employeeName: "Emily Rodriguez",
    date: "2024-12-05",
    checkIn: "09:00",
    checkOut: "18:00",
    hours: 9,
    status: "present",
  },
  {
    id: "ATT-004",
    employeeId: "E004",
    employeeName: "David Kim",
    date: "2024-12-05",
    checkIn: "08:30",
    checkOut: "17:00",
    hours: 8.5,
    status: "present",
  },
  {
    id: "ATT-005",
    employeeId: "E005",
    employeeName: "Lisa Wang",
    date: "2024-12-05",
    checkIn: null,
    checkOut: null,
    hours: 0,
    status: "on-leave",
  },
];

// todo: remove mock functionality - Complete Chart of Accounts with hierarchy
export interface ChartOfAccountsEntry {
  id: string;
  name: string;
  type: "asset" | "liability" | "equity" | "revenue" | "expense";
  level: 1 | 2 | 3;
  parentId: string | null;
  balance: number;
  isPostable: boolean;
}

export const mockAccounts: ChartOfAccountsEntry[] = [
  // ASSETS (1000-1999)
  {
    id: "1000",
    name: "Assets",
    type: "asset",
    level: 1,
    parentId: null,
    balance: 0,
    isPostable: false,
  },

  // Current Assets (1100-1199)
  {
    id: "1100",
    name: "Current Assets",
    type: "asset",
    level: 2,
    parentId: "1000",
    balance: 0,
    isPostable: false,
  },

  // Cash & Bank (1110-1119)
  {
    id: "1110",
    name: "Cash & Bank",
    type: "asset",
    level: 2,
    parentId: "1100",
    balance: 0,
    isPostable: false,
  },
  {
    id: "1111",
    name: "Cash on Hand",
    type: "asset",
    level: 3,
    parentId: "1110",
    balance: 15000,
    isPostable: true,
  },
  {
    id: "1112",
    name: "Petty Cash",
    type: "asset",
    level: 3,
    parentId: "1110",
    balance: 2500,
    isPostable: true,
  },
  {
    id: "1113",
    name: "Checking Account - Main",
    type: "asset",
    level: 3,
    parentId: "1110",
    balance: 85000,
    isPostable: true,
  },
  {
    id: "1114",
    name: "Savings Account",
    type: "asset",
    level: 3,
    parentId: "1110",
    balance: 45000,
    isPostable: true,
  },
  {
    id: "1115",
    name: "Money Market Account",
    type: "asset",
    level: 3,
    parentId: "1110",
    balance: 25000,
    isPostable: true,
  },

  // Accounts Receivable (1120-1129)
  {
    id: "1120",
    name: "Accounts Receivable",
    type: "asset",
    level: 2,
    parentId: "1100",
    balance: 0,
    isPostable: false,
  },
  {
    id: "1121",
    name: "Trade Receivables",
    type: "asset",
    level: 3,
    parentId: "1120",
    balance: 45600,
    isPostable: true,
  },
  {
    id: "1122",
    name: "Employee Receivables",
    type: "asset",
    level: 3,
    parentId: "1120",
    balance: 3200,
    isPostable: true,
  },
  {
    id: "1123",
    name: "Allowance for Doubtful Accounts",
    type: "asset",
    level: 3,
    parentId: "1120",
    balance: -2500,
    isPostable: true,
  },
  {
    id: "1124",
    name: "Notes Receivable - Short Term",
    type: "asset",
    level: 3,
    parentId: "1120",
    balance: 12000,
    isPostable: true,
  },

  // Inventory (1130-1139)
  {
    id: "1130",
    name: "Inventory",
    type: "asset",
    level: 2,
    parentId: "1100",
    balance: 0,
    isPostable: false,
  },
  {
    id: "1131",
    name: "Raw Materials",
    type: "asset",
    level: 3,
    parentId: "1130",
    balance: 78500,
    isPostable: true,
  },
  {
    id: "1132",
    name: "Work in Progress",
    type: "asset",
    level: 3,
    parentId: "1130",
    balance: 45000,
    isPostable: true,
  },
  {
    id: "1133",
    name: "Finished Goods",
    type: "asset",
    level: 3,
    parentId: "1130",
    balance: 98000,
    isPostable: true,
  },
  {
    id: "1134",
    name: "Merchandise Inventory",
    type: "asset",
    level: 3,
    parentId: "1130",
    balance: 67000,
    isPostable: true,
  },
  {
    id: "1135",
    name: "Inventory Reserve",
    type: "asset",
    level: 3,
    parentId: "1130",
    balance: -5000,
    isPostable: true,
  },

  // Other Current Assets (1140-1149)
  {
    id: "1140",
    name: "Other Current Assets",
    type: "asset",
    level: 2,
    parentId: "1100",
    balance: 0,
    isPostable: false,
  },
  {
    id: "1141",
    name: "Prepaid Insurance",
    type: "asset",
    level: 3,
    parentId: "1140",
    balance: 8500,
    isPostable: true,
  },
  {
    id: "1142",
    name: "Prepaid Rent",
    type: "asset",
    level: 3,
    parentId: "1140",
    balance: 12000,
    isPostable: true,
  },
  {
    id: "1143",
    name: "Prepaid Expenses - Other",
    type: "asset",
    level: 3,
    parentId: "1140",
    balance: 4500,
    isPostable: true,
  },

  // Fixed Assets (1200-1299)
  {
    id: "1200",
    name: "Fixed Assets",
    type: "asset",
    level: 2,
    parentId: "1000",
    balance: 0,
    isPostable: false,
  },
  {
    id: "1210",
    name: "Land",
    type: "asset",
    level: 3,
    parentId: "1200",
    balance: 150000,
    isPostable: true,
  },
  {
    id: "1220",
    name: "Buildings",
    type: "asset",
    level: 3,
    parentId: "1200",
    balance: 450000,
    isPostable: true,
  },
  {
    id: "1221",
    name: "Accumulated Depreciation - Buildings",
    type: "asset",
    level: 3,
    parentId: "1200",
    balance: -95000,
    isPostable: true,
  },
  {
    id: "1230",
    name: "Machinery & Equipment",
    type: "asset",
    level: 3,
    parentId: "1200",
    balance: 285000,
    isPostable: true,
  },
  {
    id: "1231",
    name: "Accumulated Depreciation - Machinery",
    type: "asset",
    level: 3,
    parentId: "1200",
    balance: -78000,
    isPostable: true,
  },
  {
    id: "1240",
    name: "Vehicles",
    type: "asset",
    level: 3,
    parentId: "1200",
    balance: 125000,
    isPostable: true,
  },
  {
    id: "1241",
    name: "Accumulated Depreciation - Vehicles",
    type: "asset",
    level: 3,
    parentId: "1200",
    balance: -45000,
    isPostable: true,
  },
  {
    id: "1250",
    name: "Furniture & Fixtures",
    type: "asset",
    level: 3,
    parentId: "1200",
    balance: 65000,
    isPostable: true,
  },
  {
    id: "1251",
    name: "Accumulated Depreciation - Furniture",
    type: "asset",
    level: 3,
    parentId: "1200",
    balance: -18000,
    isPostable: true,
  },
  {
    id: "1260",
    name: "Computer Equipment",
    type: "asset",
    level: 3,
    parentId: "1200",
    balance: 85000,
    isPostable: true,
  },
  {
    id: "1261",
    name: "Accumulated Depreciation - Computers",
    type: "asset",
    level: 3,
    parentId: "1200",
    balance: -32000,
    isPostable: true,
  },

  // LIABILITIES (2000-2999)
  {
    id: "2000",
    name: "Liabilities",
    type: "liability",
    level: 1,
    parentId: null,
    balance: 0,
    isPostable: false,
  },

  // Current Liabilities (2100-2199)
  {
    id: "2100",
    name: "Current Liabilities",
    type: "liability",
    level: 2,
    parentId: "2000",
    balance: 0,
    isPostable: false,
  },

  // Accounts Payable (2110-2119)
  {
    id: "2110",
    name: "Accounts Payable",
    type: "liability",
    level: 2,
    parentId: "2100",
    balance: 0,
    isPostable: false,
  },
  {
    id: "2111",
    name: "Trade Payables",
    type: "liability",
    level: 3,
    parentId: "2110",
    balance: 28900,
    isPostable: true,
  },
  {
    id: "2112",
    name: "Vendor Advances",
    type: "liability",
    level: 3,
    parentId: "2110",
    balance: 5500,
    isPostable: true,
  },
  {
    id: "2113",
    name: "Notes Payable - Short Term",
    type: "liability",
    level: 3,
    parentId: "2110",
    balance: 15000,
    isPostable: true,
  },

  // Accrued Expenses (2120-2129)
  {
    id: "2120",
    name: "Accrued Expenses",
    type: "liability",
    level: 2,
    parentId: "2100",
    balance: 0,
    isPostable: false,
  },
  {
    id: "2121",
    name: "Accrued Salaries & Wages",
    type: "liability",
    level: 3,
    parentId: "2120",
    balance: 18500,
    isPostable: true,
  },
  {
    id: "2122",
    name: "Accrued Payroll Taxes",
    type: "liability",
    level: 3,
    parentId: "2120",
    balance: 7200,
    isPostable: true,
  },
  {
    id: "2123",
    name: "Accrued Interest",
    type: "liability",
    level: 3,
    parentId: "2120",
    balance: 3400,
    isPostable: true,
  },
  {
    id: "2124",
    name: "Accrued Utilities",
    type: "liability",
    level: 3,
    parentId: "2120",
    balance: 2800,
    isPostable: true,
  },

  // Taxes Payable (2130-2139)
  {
    id: "2130",
    name: "Taxes Payable",
    type: "liability",
    level: 2,
    parentId: "2100",
    balance: 0,
    isPostable: false,
  },
  {
    id: "2131",
    name: "Sales Tax Payable",
    type: "liability",
    level: 3,
    parentId: "2130",
    balance: 8900,
    isPostable: true,
  },
  {
    id: "2132",
    name: "Income Tax Payable",
    type: "liability",
    level: 3,
    parentId: "2130",
    balance: 22000,
    isPostable: true,
  },
  {
    id: "2133",
    name: "Payroll Tax Payable",
    type: "liability",
    level: 3,
    parentId: "2130",
    balance: 6500,
    isPostable: true,
  },

  // Other Current Liabilities (2140-2149)
  {
    id: "2140",
    name: "Other Current Liabilities",
    type: "liability",
    level: 2,
    parentId: "2100",
    balance: 0,
    isPostable: false,
  },
  {
    id: "2141",
    name: "Customer Deposits",
    type: "liability",
    level: 3,
    parentId: "2140",
    balance: 12500,
    isPostable: true,
  },
  {
    id: "2142",
    name: "Unearned Revenue",
    type: "liability",
    level: 3,
    parentId: "2140",
    balance: 8000,
    isPostable: true,
  },
  {
    id: "2143",
    name: "Current Portion - Long Term Debt",
    type: "liability",
    level: 3,
    parentId: "2140",
    balance: 24000,
    isPostable: true,
  },

  // Long-Term Liabilities (2200-2299)
  {
    id: "2200",
    name: "Long-Term Liabilities",
    type: "liability",
    level: 2,
    parentId: "2000",
    balance: 0,
    isPostable: false,
  },
  {
    id: "2210",
    name: "Bank Loans - Long Term",
    type: "liability",
    level: 3,
    parentId: "2200",
    balance: 150000,
    isPostable: true,
  },
  {
    id: "2220",
    name: "Mortgage Payable",
    type: "liability",
    level: 3,
    parentId: "2200",
    balance: 280000,
    isPostable: true,
  },
  {
    id: "2230",
    name: "Equipment Loans",
    type: "liability",
    level: 3,
    parentId: "2200",
    balance: 75000,
    isPostable: true,
  },

  // EQUITY (3000-3999)
  {
    id: "3000",
    name: "Equity",
    type: "equity",
    level: 1,
    parentId: null,
    balance: 0,
    isPostable: false,
  },

  // Owner's Equity (3100-3199)
  {
    id: "3100",
    name: "Owner's Equity",
    type: "equity",
    level: 2,
    parentId: "3000",
    balance: 0,
    isPostable: false,
  },
  {
    id: "3110",
    name: "Common Stock",
    type: "equity",
    level: 3,
    parentId: "3100",
    balance: 200000,
    isPostable: true,
  },
  {
    id: "3120",
    name: "Preferred Stock",
    type: "equity",
    level: 3,
    parentId: "3100",
    balance: 50000,
    isPostable: true,
  },
  {
    id: "3130",
    name: "Additional Paid-in Capital",
    type: "equity",
    level: 3,
    parentId: "3100",
    balance: 75000,
    isPostable: true,
  },
  {
    id: "3140",
    name: "Owner's Contributions",
    type: "equity",
    level: 3,
    parentId: "3100",
    balance: 100000,
    isPostable: true,
  },
  {
    id: "3150",
    name: "Owner's Drawings",
    type: "equity",
    level: 3,
    parentId: "3100",
    balance: -25000,
    isPostable: true,
  },

  // Retained Earnings (3200-3299)
  {
    id: "3200",
    name: "Retained Earnings",
    type: "equity",
    level: 2,
    parentId: "3000",
    balance: 0,
    isPostable: false,
  },
  {
    id: "3210",
    name: "Retained Earnings - Prior Years",
    type: "equity",
    level: 3,
    parentId: "3200",
    balance: 185000,
    isPostable: true,
  },
  {
    id: "3220",
    name: "Current Year Earnings",
    type: "equity",
    level: 3,
    parentId: "3200",
    balance: 0,
    isPostable: true,
  },
  {
    id: "3230",
    name: "Dividends Paid",
    type: "equity",
    level: 3,
    parentId: "3200",
    balance: -15000,
    isPostable: true,
  },

  // REVENUE (4000-4999)
  {
    id: "4000",
    name: "Revenue",
    type: "revenue",
    level: 1,
    parentId: null,
    balance: 0,
    isPostable: false,
  },

  // Sales Revenue (4100-4199)
  {
    id: "4100",
    name: "Sales Revenue",
    type: "revenue",
    level: 2,
    parentId: "4000",
    balance: 0,
    isPostable: false,
  },
  {
    id: "4110",
    name: "Product Sales",
    type: "revenue",
    level: 3,
    parentId: "4100",
    balance: 485000,
    isPostable: true,
  },
  {
    id: "4120",
    name: "Service Revenue",
    type: "revenue",
    level: 3,
    parentId: "4100",
    balance: 125000,
    isPostable: true,
  },
  {
    id: "4130",
    name: "Shipping & Handling Revenue",
    type: "revenue",
    level: 3,
    parentId: "4100",
    balance: 18500,
    isPostable: true,
  },
  {
    id: "4140",
    name: "Sales Returns & Allowances",
    type: "revenue",
    level: 3,
    parentId: "4100",
    balance: -12500,
    isPostable: true,
  },
  {
    id: "4150",
    name: "Sales Discounts",
    type: "revenue",
    level: 3,
    parentId: "4100",
    balance: -8200,
    isPostable: true,
  },

  // Other Income (4200-4299)
  {
    id: "4200",
    name: "Other Income",
    type: "revenue",
    level: 2,
    parentId: "4000",
    balance: 0,
    isPostable: false,
  },
  {
    id: "4210",
    name: "Interest Income",
    type: "revenue",
    level: 3,
    parentId: "4200",
    balance: 5500,
    isPostable: true,
  },
  {
    id: "4220",
    name: "Dividend Income",
    type: "revenue",
    level: 3,
    parentId: "4200",
    balance: 2800,
    isPostable: true,
  },
  {
    id: "4230",
    name: "Rental Income",
    type: "revenue",
    level: 3,
    parentId: "4200",
    balance: 12000,
    isPostable: true,
  },
  {
    id: "4240",
    name: "Gain on Asset Sale",
    type: "revenue",
    level: 3,
    parentId: "4200",
    balance: 4500,
    isPostable: true,
  },
  {
    id: "4250",
    name: "Miscellaneous Income",
    type: "revenue",
    level: 3,
    parentId: "4200",
    balance: 1800,
    isPostable: true,
  },

  // EXPENSES (5000-5999)
  {
    id: "5000",
    name: "Expenses",
    type: "expense",
    level: 1,
    parentId: null,
    balance: 0,
    isPostable: false,
  },

  // Cost of Goods Sold (5100-5199)
  {
    id: "5100",
    name: "Cost of Goods Sold",
    type: "expense",
    level: 2,
    parentId: "5000",
    balance: 0,
    isPostable: false,
  },
  {
    id: "5110",
    name: "Cost of Materials",
    type: "expense",
    level: 3,
    parentId: "5100",
    balance: 145000,
    isPostable: true,
  },
  {
    id: "5120",
    name: "Direct Labor",
    type: "expense",
    level: 3,
    parentId: "5100",
    balance: 85000,
    isPostable: true,
  },
  {
    id: "5130",
    name: "Manufacturing Overhead",
    type: "expense",
    level: 3,
    parentId: "5100",
    balance: 42000,
    isPostable: true,
  },
  {
    id: "5140",
    name: "Freight In",
    type: "expense",
    level: 3,
    parentId: "5100",
    balance: 12500,
    isPostable: true,
  },
  {
    id: "5150",
    name: "Purchase Discounts",
    type: "expense",
    level: 3,
    parentId: "5100",
    balance: -5800,
    isPostable: true,
  },

  // Operating Expenses (5200-5299)
  {
    id: "5200",
    name: "Operating Expenses",
    type: "expense",
    level: 2,
    parentId: "5000",
    balance: 0,
    isPostable: false,
  },
  {
    id: "5210",
    name: "Rent Expense",
    type: "expense",
    level: 3,
    parentId: "5200",
    balance: 36000,
    isPostable: true,
  },
  {
    id: "5220",
    name: "Utilities Expense",
    type: "expense",
    level: 3,
    parentId: "5200",
    balance: 14500,
    isPostable: true,
  },
  {
    id: "5230",
    name: "Insurance Expense",
    type: "expense",
    level: 3,
    parentId: "5200",
    balance: 18000,
    isPostable: true,
  },
  {
    id: "5240",
    name: "Depreciation Expense",
    type: "expense",
    level: 3,
    parentId: "5200",
    balance: 45000,
    isPostable: true,
  },
  {
    id: "5250",
    name: "Repairs & Maintenance",
    type: "expense",
    level: 3,
    parentId: "5200",
    balance: 12800,
    isPostable: true,
  },
  {
    id: "5260",
    name: "Office Supplies",
    type: "expense",
    level: 3,
    parentId: "5200",
    balance: 4500,
    isPostable: true,
  },
  {
    id: "5270",
    name: "Telephone & Internet",
    type: "expense",
    level: 3,
    parentId: "5200",
    balance: 6200,
    isPostable: true,
  },
  {
    id: "5280",
    name: "Professional Fees",
    type: "expense",
    level: 3,
    parentId: "5200",
    balance: 15000,
    isPostable: true,
  },

  // Payroll Expenses (5300-5399)
  {
    id: "5300",
    name: "Payroll Expenses",
    type: "expense",
    level: 2,
    parentId: "5000",
    balance: 0,
    isPostable: false,
  },
  {
    id: "5310",
    name: "Salaries & Wages",
    type: "expense",
    level: 3,
    parentId: "5300",
    balance: 185000,
    isPostable: true,
  },
  {
    id: "5320",
    name: "Payroll Taxes",
    type: "expense",
    level: 3,
    parentId: "5300",
    balance: 28500,
    isPostable: true,
  },
  {
    id: "5330",
    name: "Employee Benefits",
    type: "expense",
    level: 3,
    parentId: "5300",
    balance: 32000,
    isPostable: true,
  },
  {
    id: "5340",
    name: "Workers Compensation",
    type: "expense",
    level: 3,
    parentId: "5300",
    balance: 8500,
    isPostable: true,
  },
  {
    id: "5350",
    name: "Training & Development",
    type: "expense",
    level: 3,
    parentId: "5300",
    balance: 5500,
    isPostable: true,
  },

  // Marketing & Admin (5400-5499)
  {
    id: "5400",
    name: "Marketing & Administrative",
    type: "expense",
    level: 2,
    parentId: "5000",
    balance: 0,
    isPostable: false,
  },
  {
    id: "5410",
    name: "Advertising & Promotion",
    type: "expense",
    level: 3,
    parentId: "5400",
    balance: 22000,
    isPostable: true,
  },
  {
    id: "5420",
    name: "Travel & Entertainment",
    type: "expense",
    level: 3,
    parentId: "5400",
    balance: 14500,
    isPostable: true,
  },
  {
    id: "5430",
    name: "Shipping & Freight Out",
    type: "expense",
    level: 3,
    parentId: "5400",
    balance: 18000,
    isPostable: true,
  },
  {
    id: "5440",
    name: "Bad Debt Expense",
    type: "expense",
    level: 3,
    parentId: "5400",
    balance: 3500,
    isPostable: true,
  },
  {
    id: "5450",
    name: "Bank Charges & Fees",
    type: "expense",
    level: 3,
    parentId: "5400",
    balance: 2800,
    isPostable: true,
  },
  {
    id: "5460",
    name: "Interest Expense",
    type: "expense",
    level: 3,
    parentId: "5400",
    balance: 12500,
    isPostable: true,
  },
  {
    id: "5470",
    name: "Licenses & Permits",
    type: "expense",
    level: 3,
    parentId: "5400",
    balance: 3200,
    isPostable: true,
  },
  {
    id: "5480",
    name: "Miscellaneous Expense",
    type: "expense",
    level: 3,
    parentId: "5400",
    balance: 4800,
    isPostable: true,
  },
];

export const mockJournalEntries = [
  {
    id: "JE-001",
    date: "2024-12-01",
    description: "Sales Revenue Recognition",
    debitAccount: "1100",
    creditAccount: "4000",
    amount: 4599.5,
    status: "posted",
  },
  {
    id: "JE-002",
    date: "2024-12-02",
    description: "Inventory Purchase",
    debitAccount: "1200",
    creditAccount: "2000",
    amount: 12500.0,
    status: "posted",
  },
  {
    id: "JE-003",
    date: "2024-12-03",
    description: "Payment Received",
    debitAccount: "1000",
    creditAccount: "1100",
    amount: 2340.0,
    status: "posted",
  },
  {
    id: "JE-004",
    date: "2024-12-04",
    description: "Operating Expense Payment",
    debitAccount: "5100",
    creditAccount: "1000",
    amount: 1500.0,
    status: "draft",
  },
];

export const mockLocations = [
  {
    id: "LOC-001",
    code: "A-01-01",
    name: "Rack A, Shelf 1, Bin 1",
    zone: "Zone A",
    type: "bin",
    capacity: 100,
    used: 45,
  },
  {
    id: "LOC-002",
    code: "A-01-02",
    name: "Rack A, Shelf 1, Bin 2",
    zone: "Zone A",
    type: "bin",
    capacity: 100,
    used: 78,
  },
  {
    id: "LOC-003",
    code: "B-02-01",
    name: "Rack B, Shelf 2, Bin 1",
    zone: "Zone B",
    type: "bin",
    capacity: 200,
    used: 12,
  },
  {
    id: "LOC-004",
    code: "B-02-02",
    name: "Rack B, Shelf 2, Bin 2",
    zone: "Zone B",
    type: "bin",
    capacity: 200,
    used: 156,
  },
  {
    id: "LOC-005",
    code: "C-03-01",
    name: "Bulk Storage C, Area 1",
    zone: "Zone C",
    type: "bulk",
    capacity: 5000,
    used: 2450,
  },
];

export const mockMovements: Movement[] = [
  {
    id: "MOV-001",
    type: "IN",
    productId: "P001",
    productName: "Industrial Widget A",
    quantity: 100,
    fromLocation: null,
    toLocation: "A-01-01",
    date: "2024-12-01",
    reference: "PO-001",
  },
  {
    id: "MOV-002",
    type: "OUT",
    productId: "P002",
    productName: "Industrial Widget B",
    quantity: 25,
    fromLocation: "A-01-02",
    toLocation: null,
    date: "2024-12-02",
    reference: "SO-001",
  },
  {
    id: "MOV-003",
    type: "TRANSFER",
    productId: "P003",
    productName: "Component Alpha",
    quantity: 50,
    fromLocation: "B-02-01",
    toLocation: "D-01-01",
    date: "2024-12-03",
    reference: "INT-001",
  },
  {
    id: "MOV-004",
    type: "IN",
    productId: "P005",
    productName: "Raw Material X",
    quantity: 500,
    fromLocation: null,
    toLocation: "C-03-01",
    date: "2024-12-04",
    reference: "PO-002",
  },
];

export const mockDashboardStats = {
  sales: { today: 12500, month: 156000, pending: 8, trend: 12.5 },
  inventory: { totalValue: 234500, lowStock: 3, movements: 24, trend: -2.3 },
  receivables: { total: 45600, overdue: 8900, collected: 23400, trend: 5.8 },
  payables: { total: 28900, dueThisWeek: 12500, paid: 45000, trend: -8.2 },
};

// ============================================================================
// MOCK DATA FOR INTEGRATED MODULES (Demo Mode without Backend)
// ============================================================================

// Mock Companies (multi-company hierarchy)
export const mockCompanies = [
  // HOLDING COMPANIES (Level 1)
  {
    id: "comp-001",
    code: "UNANZA-HQ",
    name: "Unanza Holdings",
    legalName: "Unanza Holdings Pte Ltd",
    companyType: "holding" as const,
    level: 1,
    parentId: null,
    rootId: "comp-001",
    path: "/comp-001",
    currency: "USD",
    taxId: "US-123456789",
    address: "1000 Corporate Blvd",
    city: "New York",
    country: "United States",
    phone: "+1-212-555-0100",
    email: "info@unanza.com",
    website: "https://www.unanza.com",
    locale: "en-US",
    timezone: "America/New_York",
    isActive: true,
    consolidationEnabled: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "comp-010",
    code: "TECHGLOBAL",
    name: "TechGlobal Group",
    legalName: "TechGlobal Group Limited",
    companyType: "holding" as const,
    level: 1,
    parentId: null,
    rootId: "comp-010",
    path: "/comp-010",
    currency: "GBP",
    taxId: "GB-987654321",
    address: "250 Bishopsgate",
    city: "London",
    country: "United Kingdom",
    phone: "+44-20-7946-0958",
    email: "contact@techglobal.co.uk",
    website: "https://www.techglobal.co.uk",
    locale: "en-GB",
    timezone: "Europe/London",
    isActive: true,
    consolidationEnabled: true,
    createdAt: new Date("2023-06-15"),
    updatedAt: new Date("2024-01-01"),
  },

  // SUBSIDIARIES under Unanza Holdings (Level 2)
  {
    id: "comp-002",
    code: "UNANZA-US",
    name: "Unanza USA",
    legalName: "Unanza USA Inc",
    companyType: "subsidiary" as const,
    level: 2,
    parentId: "comp-001",
    rootId: "comp-001",
    path: "/comp-001/comp-002",
    currency: "USD",
    taxId: "US-234567890",
    address: "500 Technology Drive",
    city: "San Francisco",
    country: "United States",
    phone: "+1-415-555-0200",
    email: "usa@unanza.com",
    website: "https://usa.unanza.com",
    locale: "en-US",
    timezone: "America/Los_Angeles",
    isActive: true,
    consolidationEnabled: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "comp-003",
    code: "UNANZA-EU",
    name: "Unanza Europe",
    legalName: "Unanza Europe GmbH",
    companyType: "subsidiary" as const,
    level: 2,
    parentId: "comp-001",
    rootId: "comp-001",
    path: "/comp-001/comp-003",
    currency: "EUR",
    taxId: "DE-345678901",
    address: "Berliner Strasse 100",
    city: "Berlin",
    country: "Germany",
    phone: "+49-30-5555-0300",
    email: "europe@unanza.com",
    website: "https://europe.unanza.com",
    locale: "de-DE",
    timezone: "Europe/Berlin",
    isActive: true,
    consolidationEnabled: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "comp-004",
    code: "UNANZA-ASIA",
    name: "Unanza Asia Pacific",
    legalName: "Unanza Asia Pacific Pte Ltd",
    companyType: "subsidiary" as const,
    level: 2,
    parentId: "comp-001",
    rootId: "comp-001",
    path: "/comp-001/comp-004",
    currency: "SGD",
    taxId: "SG-456789012",
    address: "1 Marina Boulevard",
    city: "Singapore",
    country: "Singapore",
    phone: "+65-6555-0400",
    email: "asia@unanza.com",
    website: "https://asia.unanza.com",
    locale: "en-SG",
    timezone: "Asia/Singapore",
    isActive: true,
    consolidationEnabled: true,
    createdAt: new Date("2024-02-15"),
    updatedAt: new Date("2024-02-15"),
  },

  // SUBSIDIARIES under TechGlobal Group (Level 2)
  {
    id: "comp-011",
    code: "TECHGLOBAL-UK",
    name: "TechGlobal UK",
    legalName: "TechGlobal UK Ltd",
    companyType: "subsidiary" as const,
    level: 2,
    parentId: "comp-010",
    rootId: "comp-010",
    path: "/comp-010/comp-011",
    currency: "GBP",
    taxId: "GB-111222333",
    address: "100 Oxford Street",
    city: "Manchester",
    country: "United Kingdom",
    phone: "+44-161-555-0110",
    email: "uk@techglobal.co.uk",
    website: "https://uk.techglobal.co.uk",
    locale: "en-GB",
    timezone: "Europe/London",
    isActive: true,
    consolidationEnabled: true,
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "comp-012",
    code: "TECHGLOBAL-FR",
    name: "TechGlobal France",
    legalName: "TechGlobal France SARL",
    companyType: "subsidiary" as const,
    level: 2,
    parentId: "comp-010",
    rootId: "comp-010",
    path: "/comp-010/comp-012",
    currency: "EUR",
    taxId: "FR-444555666",
    address: "75 Avenue des Champs-Élysées",
    city: "Paris",
    country: "France",
    phone: "+33-1-5555-0120",
    email: "france@techglobal.fr",
    website: "https://france.techglobal.fr",
    locale: "fr-FR",
    timezone: "Europe/Paris",
    isActive: true,
    consolidationEnabled: true,
    createdAt: new Date("2023-08-10"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "comp-013",
    code: "TECHGLOBAL-JP",
    name: "TechGlobal Japan",
    legalName: "TechGlobal Japan KK",
    companyType: "subsidiary" as const,
    level: 2,
    parentId: "comp-010",
    rootId: "comp-010",
    path: "/comp-010/comp-013",
    currency: "JPY",
    taxId: "JP-777888999",
    address: "1-1-1 Shibuya",
    city: "Tokyo",
    country: "Japan",
    phone: "+81-3-5555-0130",
    email: "japan@techglobal.jp",
    website: "https://japan.techglobal.jp",
    locale: "ja-JP",
    timezone: "Asia/Tokyo",
    isActive: true,
    consolidationEnabled: true,
    createdAt: new Date("2023-09-20"),
    updatedAt: new Date("2024-01-01"),
  },

  // BRANCHES under Unanza USA (Level 3)
  {
    id: "comp-005",
    code: "UNANZA-NYC",
    name: "Unanza NYC Office",
    legalName: "Unanza USA Inc - NYC Branch",
    companyType: "branch" as const,
    level: 3,
    parentId: "comp-002",
    rootId: "comp-001",
    path: "/comp-001/comp-002/comp-005",
    currency: "USD",
    taxId: "US-234567890-NYC",
    address: "350 Fifth Avenue",
    city: "New York",
    country: "United States",
    phone: "+1-212-555-0500",
    email: "nyc@unanza.com",
    locale: "en-US",
    timezone: "America/New_York",
    isActive: true,
    consolidationEnabled: false,
    createdAt: new Date("2024-03-01"),
    updatedAt: new Date("2024-03-01"),
  },
  {
    id: "comp-006",
    code: "UNANZA-LA",
    name: "Unanza LA Office",
    legalName: "Unanza USA Inc - LA Branch",
    companyType: "branch" as const,
    level: 3,
    parentId: "comp-002",
    rootId: "comp-001",
    path: "/comp-001/comp-002/comp-006",
    currency: "USD",
    taxId: "US-234567890-LA",
    address: "1000 Wilshire Boulevard",
    city: "Los Angeles",
    country: "United States",
    phone: "+1-310-555-0600",
    email: "la@unanza.com",
    locale: "en-US",
    timezone: "America/Los_Angeles",
    isActive: true,
    consolidationEnabled: false,
    createdAt: new Date("2024-04-15"),
    updatedAt: new Date("2024-04-15"),
  },

  // BRANCHES under Unanza Europe (Level 3)
  {
    id: "comp-007",
    code: "UNANZA-MUN",
    name: "Unanza Munich Office",
    legalName: "Unanza Europe GmbH - Munich",
    companyType: "branch" as const,
    level: 3,
    parentId: "comp-003",
    rootId: "comp-001",
    path: "/comp-001/comp-003/comp-007",
    currency: "EUR",
    taxId: "DE-345678901-MUC",
    address: "Maximilianstrasse 50",
    city: "Munich",
    country: "Germany",
    phone: "+49-89-5555-0700",
    email: "munich@unanza.com",
    locale: "de-DE",
    timezone: "Europe/Berlin",
    isActive: true,
    consolidationEnabled: false,
    createdAt: new Date("2024-05-01"),
    updatedAt: new Date("2024-05-01"),
  },
  {
    id: "comp-008",
    code: "UNANZA-AMS",
    name: "Unanza Amsterdam Office",
    legalName: "Unanza Europe GmbH - Amsterdam",
    companyType: "branch" as const,
    level: 3,
    parentId: "comp-003",
    rootId: "comp-001",
    path: "/comp-001/comp-003/comp-008",
    currency: "EUR",
    taxId: "NL-567890123",
    address: "Keizersgracht 555",
    city: "Amsterdam",
    country: "Netherlands",
    phone: "+31-20-5555-0800",
    email: "amsterdam@unanza.com",
    locale: "nl-NL",
    timezone: "Europe/Amsterdam",
    isActive: true,
    consolidationEnabled: false,
    createdAt: new Date("2024-06-01"),
    updatedAt: new Date("2024-06-01"),
  },

  // BRANCHES under Unanza Asia Pacific (Level 3)
  {
    id: "comp-009",
    code: "UNANZA-JKT",
    name: "Unanza Jakarta Office",
    legalName: "Unanza Asia Pacific - Jakarta",
    companyType: "branch" as const,
    level: 3,
    parentId: "comp-004",
    rootId: "comp-001",
    path: "/comp-001/comp-004/comp-009",
    currency: "IDR",
    taxId: "ID-678901234",
    address: "Jl. Sudirman Kav 52-53",
    city: "Jakarta",
    country: "Indonesia",
    phone: "+62-21-5555-0900",
    email: "jakarta@unanza.com",
    locale: "id-ID",
    timezone: "Asia/Jakarta",
    isActive: true,
    consolidationEnabled: false,
    createdAt: new Date("2024-07-01"),
    updatedAt: new Date("2024-07-01"),
  },

  // BRANCHES under TechGlobal UK (Level 3)
  {
    id: "comp-014",
    code: "TECHGLOBAL-EDI",
    name: "TechGlobal Edinburgh",
    legalName: "TechGlobal UK Ltd - Edinburgh",
    companyType: "branch" as const,
    level: 3,
    parentId: "comp-011",
    rootId: "comp-010",
    path: "/comp-010/comp-011/comp-014",
    currency: "GBP",
    taxId: "GB-111222333-EDI",
    address: "50 Princes Street",
    city: "Edinburgh",
    country: "United Kingdom",
    phone: "+44-131-555-0140",
    email: "edinburgh@techglobal.co.uk",
    locale: "en-GB",
    timezone: "Europe/London",
    isActive: true,
    consolidationEnabled: false,
    createdAt: new Date("2023-10-01"),
    updatedAt: new Date("2024-01-01"),
  },

  // BRANCHES under TechGlobal France (Level 3)
  {
    id: "comp-015",
    code: "TECHGLOBAL-LYN",
    name: "TechGlobal Lyon",
    legalName: "TechGlobal France SARL - Lyon",
    companyType: "branch" as const,
    level: 3,
    parentId: "comp-012",
    rootId: "comp-010",
    path: "/comp-010/comp-012/comp-015",
    currency: "EUR",
    taxId: "FR-444555666-LYN",
    address: "20 Rue de la République",
    city: "Lyon",
    country: "France",
    phone: "+33-4-5555-0150",
    email: "lyon@techglobal.fr",
    locale: "fr-FR",
    timezone: "Europe/Paris",
    isActive: true,
    consolidationEnabled: false,
    createdAt: new Date("2023-11-15"),
    updatedAt: new Date("2024-01-01"),
  },
];

// Mock Company Hierarchy for CompanySwitcher
export const mockCompanyHierarchy = [
  {
    company: mockCompanies[0],
    children: [
      { company: mockCompanies[1], children: [], level: 2 },
      { company: mockCompanies[2], children: [], level: 2 },
    ],
    level: 1,
  },
];

// Mock Users
export const mockUsers = [
  {
    id: "user-001",
    username: "admin",
    email: "admin@unanza.com",
    fullName: "System Administrator",
    defaultCompanyId: "comp-001",
    isActive: true,
    createdAt: new Date("2024-01-01"),
    lastLogin: new Date("2024-12-05"),
  },
  {
    id: "user-002",
    username: "john.doe",
    email: "john.doe@unanza.com",
    fullName: "John Doe",
    defaultCompanyId: "comp-002",
    isActive: true,
    createdAt: new Date("2024-02-15"),
    lastLogin: new Date("2024-12-04"),
  },
  {
    id: "user-003",
    username: "jane.smith",
    email: "jane.smith@unanza.com",
    fullName: "Jane Smith",
    defaultCompanyId: "comp-002",
    isActive: true,
    createdAt: new Date("2024-03-01"),
    lastLogin: new Date("2024-12-03"),
  },
];

// Mock Roles
export const mockRoles = [
  {
    id: "role-001",
    code: "SUPER_ADMIN",
    name: "Super Administrator",
    description: "Full system access",
    isSystemRole: true,
    permissions: ["*"],
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "role-002",
    code: "ADMIN",
    name: "Administrator",
    description: "Company administrator",
    isSystemRole: true,
    permissions: ["read:*", "write:*", "delete:*"],
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "role-003",
    code: "MANAGER",
    name: "Manager",
    description: "Department manager",
    isSystemRole: false,
    permissions: ["read:*", "write:orders", "write:inventory"],
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "role-004",
    code: "USER",
    name: "Standard User",
    description: "Regular user access",
    isSystemRole: false,
    permissions: ["read:*"],
    createdAt: new Date("2024-01-01"),
  },
];

// Mock User Company Roles (assignments)
export const mockUserCompanyRoles = [
  {
    id: "ucr-001",
    userId: "user-001",
    companyId: "comp-001",
    roleId: "role-001",
    isActive: true,
    isDefault: true,
  },
  {
    id: "ucr-002",
    userId: "user-001",
    companyId: "comp-002",
    roleId: "role-001",
    isActive: true,
    isDefault: false,
  },
  {
    id: "ucr-003",
    userId: "user-001",
    companyId: "comp-003",
    roleId: "role-001",
    isActive: true,
    isDefault: false,
  },
  {
    id: "ucr-004",
    userId: "user-002",
    companyId: "comp-002",
    roleId: "role-002",
    isActive: true,
    isDefault: true,
  },
  {
    id: "ucr-005",
    userId: "user-003",
    companyId: "comp-002",
    roleId: "role-003",
    isActive: true,
    isDefault: true,
  },
];

// Mock Warehouses (full schema for integrated WarehouseList)
export const mockWarehouses = [
  {
    id: "wh-001",
    companyId: "comp-002",
    code: "WH-MAIN",
    name: "Main Warehouse",
    warehouseType: "standard" as const,
    address: "123 Industrial Blvd",
    city: "New York",
    state: "NY",
    country: "US",
    postalCode: "10001",
    allowNegativeStock: false,
    isActive: true,
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "wh-002",
    companyId: "comp-002",
    code: "WH-TRANSIT",
    name: "Transit Warehouse",
    warehouseType: "transit" as const,
    address: "456 Logistics Way",
    city: "Chicago",
    state: "IL",
    country: "US",
    postalCode: "60601",
    allowNegativeStock: true,
    isActive: true,
    createdAt: new Date("2024-02-01"),
  },
  {
    id: "wh-003",
    companyId: "comp-002",
    code: "WH-VIRTUAL",
    name: "Virtual Stock",
    warehouseType: "virtual" as const,
    address: null,
    city: null,
    state: null,
    country: null,
    postalCode: null,
    allowNegativeStock: true,
    isActive: true,
    createdAt: new Date("2024-02-15"),
  },
];

// Mock Full Products (for integrated ProductList with company scope)
export const mockProductsFull = [
  {
    id: "prod-001",
    companyId: "comp-002",
    sku: "WDG-001",
    name: "Industrial Widget A",
    description: "High-quality industrial widget for manufacturing",
    category: "Widgets",
    uom: "EA",
    purchasePrice: 35.0,
    sellingPrice: 49.99,
    taxRate: 10,
    stockOnHand: 234,
    reorderLevel: 50,
    reorderQuantity: 100,
    isActive: true,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "prod-002",
    companyId: "comp-002",
    sku: "WDG-002",
    name: "Industrial Widget B",
    description: "Premium industrial widget",
    category: "Widgets",
    uom: "EA",
    purchasePrice: 55.0,
    sellingPrice: 79.99,
    taxRate: 10,
    stockOnHand: 156,
    reorderLevel: 30,
    reorderQuantity: 50,
    isActive: true,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "prod-003",
    companyId: "comp-002",
    sku: "CPT-001",
    name: "Component Alpha",
    description: "Essential component for assembly",
    category: "Components",
    uom: "EA",
    purchasePrice: 15.0,
    sellingPrice: 24.5,
    taxRate: 10,
    stockOnHand: 12,
    reorderLevel: 100,
    reorderQuantity: 200,
    isActive: true,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "prod-004",
    companyId: "comp-002",
    sku: "CPT-002",
    name: "Component Beta",
    description: "Box of premium components",
    category: "Components",
    uom: "BOX",
    purchasePrice: 120.0,
    sellingPrice: 189.0,
    taxRate: 10,
    stockOnHand: 89,
    reorderLevel: 20,
    reorderQuantity: 40,
    isActive: true,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "prod-005",
    companyId: "comp-002",
    sku: "MAT-001",
    name: "Raw Material X",
    description: "Bulk raw material",
    category: "Materials",
    uom: "KG",
    purchasePrice: 8.0,
    sellingPrice: 12.75,
    taxRate: 5,
    stockOnHand: 2450,
    reorderLevel: 500,
    reorderQuantity: 1000,
    isActive: true,
    createdAt: new Date("2024-01-01"),
  },
];

// Mock Full Vendors (for integrated lists)
export const mockVendorsFull = [
  {
    id: "vend-001",
    companyId: "comp-002",
    code: "PRIME",
    name: "Prime Suppliers Co.",
    contactName: "David Lee",
    email: "sales@primesuppliers.com",
    phone: "+1 555-0200",
    address: "500 Supplier Road",
    city: "Detroit",
    state: "MI",
    country: "US",
    postalCode: "48201",
    taxId: "11-2233445",
    paymentTerms: 30,
    isActive: true,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "vend-002",
    companyId: "comp-002",
    code: "QUALITY",
    name: "Quality Materials Inc.",
    contactName: "Eva Martinez",
    email: "orders@qualitymaterials.com",
    phone: "+1 555-0201",
    address: "600 Quality Lane",
    city: "Phoenix",
    state: "AZ",
    country: "US",
    postalCode: "85001",
    taxId: "22-3344556",
    paymentTerms: 45,
    isActive: true,
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "vend-003",
    companyId: "comp-002",
    code: "FAST",
    name: "FastShip Logistics",
    contactName: "Frank Wilson",
    email: "partners@fastship.com",
    phone: "+1 555-0202",
    address: "700 Logistics Parkway",
    city: "Memphis",
    state: "TN",
    country: "US",
    postalCode: "38101",
    taxId: "33-4455667",
    paymentTerms: 15,
    isActive: true,
    createdAt: new Date("2024-02-01"),
  },
];

// Mock Full Sales Orders (with all fields for integrated SalesOrderList)
export const mockSalesOrdersFull = [
  {
    id: "so-001",
    companyId: "comp-002",
    orderNumber: "SO-2024-001",
    customerId: "cust-001",
    customerName: "Acme Corporation",
    orderDate: "2024-12-01",
    expectedDeliveryDate: "2024-12-08",
    status: "invoiced" as const,
    subtotal: 4181.36,
    taxAmount: 418.14,
    total: 4599.5,
    notes: "Priority order",
    createdBy: "user-002",
    createdAt: new Date("2024-12-01"),
  },
  {
    id: "so-002",
    companyId: "comp-002",
    orderNumber: "SO-2024-002",
    customerId: "cust-002",
    customerName: "TechStart Inc.",
    orderDate: "2024-12-02",
    expectedDeliveryDate: "2024-12-09",
    status: "delivered" as const,
    subtotal: 2127.27,
    taxAmount: 212.73,
    total: 2340.0,
    notes: "",
    createdBy: "user-002",
    createdAt: new Date("2024-12-02"),
  },
  {
    id: "so-003",
    companyId: "comp-002",
    orderNumber: "SO-2024-003",
    customerId: "cust-003",
    customerName: "Global Supplies Ltd",
    orderDate: "2024-12-03",
    expectedDeliveryDate: "2024-12-10",
    status: "confirmed" as const,
    subtotal: 7954.55,
    taxAmount: 795.45,
    total: 8750.0,
    notes: "Bulk order",
    createdBy: "user-003",
    createdAt: new Date("2024-12-03"),
  },
  {
    id: "so-004",
    companyId: "comp-002",
    orderNumber: "SO-2024-004",
    customerId: "cust-001",
    customerName: "Acme Corporation",
    orderDate: "2024-12-04",
    expectedDeliveryDate: "2024-12-11",
    status: "draft" as const,
    subtotal: 1136.36,
    taxAmount: 113.64,
    total: 1250.0,
    notes: "",
    createdBy: "user-002",
    createdAt: new Date("2024-12-04"),
  },
];

// Mock Sales Order Lines
export const mockSalesOrderLines = [
  {
    id: "sol-001",
    salesOrderId: "so-001",
    productId: "prod-001",
    productName: "Industrial Widget A",
    quantity: 50,
    unitPrice: 49.99,
    taxRate: 10,
    lineTotal: 2749.45,
  },
  {
    id: "sol-002",
    salesOrderId: "so-001",
    productId: "prod-002",
    productName: "Industrial Widget B",
    quantity: 20,
    unitPrice: 79.99,
    taxRate: 10,
    lineTotal: 1759.78,
  },
  {
    id: "sol-003",
    salesOrderId: "so-002",
    productId: "prod-003",
    productName: "Component Alpha",
    quantity: 80,
    unitPrice: 24.5,
    taxRate: 10,
    lineTotal: 2156.0,
  },
  {
    id: "sol-004",
    salesOrderId: "so-003",
    productId: "prod-001",
    productName: "Industrial Widget A",
    quantity: 100,
    unitPrice: 49.99,
    taxRate: 10,
    lineTotal: 5498.9,
  },
  {
    id: "sol-005",
    salesOrderId: "so-003",
    productId: "prod-004",
    productName: "Component Beta",
    quantity: 15,
    unitPrice: 189.0,
    taxRate: 10,
    lineTotal: 3118.5,
  },
  {
    id: "sol-006",
    salesOrderId: "so-004",
    productId: "prod-002",
    productName: "Industrial Widget B",
    quantity: 15,
    unitPrice: 79.99,
    taxRate: 10,
    lineTotal: 1319.84,
  },
];

// Mock Full Purchase Orders (for integrated PurchaseOrderList)
export const mockPurchaseOrdersFull = [
  {
    id: "po-001",
    companyId: "comp-002",
    orderNumber: "PO-2024-001",
    vendorId: "vend-001",
    vendorName: "Prime Suppliers Co.",
    orderDate: "2024-12-01",
    expectedDeliveryDate: "2024-12-15",
    status: "received" as const,
    subtotal: 11363.64,
    taxAmount: 1136.36,
    total: 12500.0,
    notes: "Quarterly replenishment",
    createdBy: "user-002",
    createdAt: new Date("2024-12-01"),
  },
  {
    id: "po-002",
    companyId: "comp-002",
    orderNumber: "PO-2024-002",
    vendorId: "vend-002",
    vendorName: "Quality Materials Inc.",
    orderDate: "2024-12-02",
    expectedDeliveryDate: "2024-12-20",
    status: "ordered" as const,
    subtotal: 8090.91,
    taxAmount: 809.09,
    total: 8900.0,
    notes: "",
    createdBy: "user-003",
    createdAt: new Date("2024-12-02"),
  },
  {
    id: "po-003",
    companyId: "comp-002",
    orderNumber: "PO-2024-003",
    vendorId: "vend-001",
    vendorName: "Prime Suppliers Co.",
    orderDate: "2024-12-03",
    expectedDeliveryDate: "2024-12-18",
    status: "draft" as const,
    subtotal: 5090.91,
    taxAmount: 509.09,
    total: 5600.0,
    notes: "Pending approval",
    createdBy: "user-002",
    createdAt: new Date("2024-12-03"),
  },
];

// Mock Purchase Order Lines
export const mockPurchaseOrderLines = [
  {
    id: "pol-001",
    purchaseOrderId: "po-001",
    productId: "prod-001",
    productName: "Industrial Widget A",
    quantity: 200,
    unitPrice: 35.0,
    taxRate: 10,
    lineTotal: 7700.0,
  },
  {
    id: "pol-002",
    purchaseOrderId: "po-001",
    productId: "prod-003",
    productName: "Component Alpha",
    quantity: 300,
    unitPrice: 15.0,
    taxRate: 10,
    lineTotal: 4950.0,
  },
  {
    id: "pol-003",
    purchaseOrderId: "po-002",
    productId: "prod-005",
    productName: "Raw Material X",
    quantity: 1000,
    unitPrice: 8.0,
    taxRate: 5,
    lineTotal: 8400.0,
  },
  {
    id: "pol-004",
    purchaseOrderId: "po-003",
    productId: "prod-002",
    productName: "Industrial Widget B",
    quantity: 100,
    unitPrice: 55.0,
    taxRate: 10,
    lineTotal: 6050.0,
  },
];

// Mock Chart of Accounts (full schema for integrated ChartOfAccounts)
export const mockAccountsFull = [
  {
    id: "acc-1000",
    companyId: "comp-002",
    code: "1000",
    name: "Assets",
    accountType: "asset",
    parentId: null,
    level: 1,
    balance: 0,
    isPostable: false,
    isActive: true,
  },
  {
    id: "acc-1100",
    companyId: "comp-002",
    code: "1100",
    name: "Current Assets",
    accountType: "asset",
    parentId: "acc-1000",
    level: 2,
    balance: 0,
    isPostable: false,
    isActive: true,
  },
  {
    id: "acc-1110",
    companyId: "comp-002",
    code: "1110",
    name: "Cash & Bank",
    accountType: "asset",
    parentId: "acc-1100",
    level: 3,
    balance: 85000,
    isPostable: true,
    isActive: true,
  },
  {
    id: "acc-1120",
    companyId: "comp-002",
    code: "1120",
    name: "Accounts Receivable",
    accountType: "asset",
    parentId: "acc-1100",
    level: 3,
    balance: 45600,
    isPostable: true,
    isActive: true,
  },
  {
    id: "acc-1130",
    companyId: "comp-002",
    code: "1130",
    name: "Inventory",
    accountType: "asset",
    parentId: "acc-1100",
    level: 3,
    balance: 234500,
    isPostable: true,
    isActive: true,
  },
  {
    id: "acc-2000",
    companyId: "comp-002",
    code: "2000",
    name: "Liabilities",
    accountType: "liability",
    parentId: null,
    level: 1,
    balance: 0,
    isPostable: false,
    isActive: true,
  },
  {
    id: "acc-2100",
    companyId: "comp-002",
    code: "2100",
    name: "Current Liabilities",
    accountType: "liability",
    parentId: "acc-2000",
    level: 2,
    balance: 0,
    isPostable: false,
    isActive: true,
  },
  {
    id: "acc-2110",
    companyId: "comp-002",
    code: "2110",
    name: "Accounts Payable",
    accountType: "liability",
    parentId: "acc-2100",
    level: 3,
    balance: 28900,
    isPostable: true,
    isActive: true,
  },
  {
    id: "acc-3000",
    companyId: "comp-002",
    code: "3000",
    name: "Equity",
    accountType: "equity",
    parentId: null,
    level: 1,
    balance: 0,
    isPostable: false,
    isActive: true,
  },
  {
    id: "acc-3100",
    companyId: "comp-002",
    code: "3100",
    name: "Retained Earnings",
    accountType: "equity",
    parentId: "acc-3000",
    level: 2,
    balance: 185000,
    isPostable: true,
    isActive: true,
  },
  {
    id: "acc-4000",
    companyId: "comp-002",
    code: "4000",
    name: "Revenue",
    accountType: "revenue",
    parentId: null,
    level: 1,
    balance: 0,
    isPostable: false,
    isActive: true,
  },
  {
    id: "acc-4100",
    companyId: "comp-002",
    code: "4100",
    name: "Sales Revenue",
    accountType: "revenue",
    parentId: "acc-4000",
    level: 2,
    balance: 485000,
    isPostable: true,
    isActive: true,
  },
  {
    id: "acc-5000",
    companyId: "comp-002",
    code: "5000",
    name: "Expenses",
    accountType: "expense",
    parentId: null,
    level: 1,
    balance: 0,
    isPostable: false,
    isActive: true,
  },
  {
    id: "acc-5100",
    companyId: "comp-002",
    code: "5100",
    name: "Cost of Goods Sold",
    accountType: "expense",
    parentId: "acc-5000",
    level: 2,
    balance: 145000,
    isPostable: true,
    isActive: true,
  },
  {
    id: "acc-5200",
    companyId: "comp-002",
    code: "5200",
    name: "Operating Expenses",
    accountType: "expense",
    parentId: "acc-5000",
    level: 2,
    balance: 85000,
    isPostable: true,
    isActive: true,
  },
];

// Mock Vendor Scorecard data for reports
export const mockVendorScorecard = [
  {
    vendorId: "vend-001",
    vendorName: "Prime Suppliers Co.",
    onTimeDelivery: 95,
    qualityScore: 92,
    priceCompetitiveness: 88,
    overallScore: 92,
  },
  {
    vendorId: "vend-002",
    vendorName: "Quality Materials Inc.",
    onTimeDelivery: 88,
    qualityScore: 96,
    priceCompetitiveness: 82,
    overallScore: 89,
  },
  {
    vendorId: "vend-003",
    vendorName: "FastShip Logistics",
    onTimeDelivery: 98,
    qualityScore: 85,
    priceCompetitiveness: 90,
    overallScore: 91,
  },
];

// Mock Customer Lifetime Value data
export const mockCustomerLifetimeValue = [
  {
    customerId: "cust-001",
    customerName: "Acme Corporation",
    clv: 125000,
    segment: "high",
    purchaseFrequency: 12,
    avgOrderValue: 4500,
  },
  {
    customerId: "cust-002",
    customerName: "TechStart Inc.",
    clv: 67500,
    segment: "medium",
    purchaseFrequency: 8,
    avgOrderValue: 2800,
  },
  {
    customerId: "cust-003",
    customerName: "Global Supplies Ltd",
    clv: 234000,
    segment: "high",
    purchaseFrequency: 24,
    avgOrderValue: 8500,
  },
];

// Mock Audit Log
export const mockAuditLog = [
  {
    id: "audit-001",
    timestamp: "2024-12-05T10:30:00Z",
    userId: "user-002",
    userName: "John Doe",
    action: "CREATE",
    entity: "SalesOrder",
    entityId: "so-004",
    details: "Created sales order SO-2024-004",
  },
  {
    id: "audit-002",
    timestamp: "2024-12-05T09:15:00Z",
    userId: "user-003",
    userName: "Jane Smith",
    action: "UPDATE",
    entity: "Product",
    entityId: "prod-001",
    details: "Updated stock level from 200 to 234",
  },
  {
    id: "audit-003",
    timestamp: "2024-12-04T16:45:00Z",
    userId: "user-002",
    userName: "John Doe",
    action: "CONFIRM",
    entity: "SalesOrder",
    entityId: "so-003",
    details: "Confirmed sales order SO-2024-003",
  },
  {
    id: "audit-004",
    timestamp: "2024-12-04T14:20:00Z",
    userId: "user-001",
    userName: "System Administrator",
    action: "CREATE",
    entity: "User",
    entityId: "user-003",
    details: "Created new user jane.smith",
  },
];

// Mock Churn Probability
export const mockChurnProbability = [
  {
    customerId: "cust-001",
    customerName: "Acme Corporation",
    churnProbability: 5,
    lastPurchase: "2024-12-01",
    riskLevel: "low",
  },
  {
    customerId: "cust-002",
    customerName: "TechStart Inc.",
    churnProbability: 25,
    lastPurchase: "2024-11-15",
    riskLevel: "medium",
  },
  {
    customerId: "cust-003",
    customerName: "Global Supplies Ltd",
    churnProbability: 2,
    lastPurchase: "2024-12-03",
    riskLevel: "low",
  },
];

// Mock Predictive Reorder
export const mockPredictiveReorder = [
  {
    productId: "prod-003",
    productName: "Component Alpha",
    currentStock: 12,
    predictedDemand: 150,
    suggestedReorder: 200,
    urgency: "high",
  },
  {
    productId: "prod-004",
    productName: "Component Beta",
    currentStock: 89,
    predictedDemand: 45,
    suggestedReorder: 40,
    urgency: "low",
  },
  {
    productId: "prod-001",
    productName: "Industrial Widget A",
    currentStock: 234,
    predictedDemand: 100,
    suggestedReorder: 100,
    urgency: "medium",
  },
];

// Mock Demand Forecast
export const mockDemandForecast = [
  {
    productId: "prod-001",
    productName: "Industrial Widget A",
    currentMonth: 100,
    nextMonth: 120,
    trend: "up",
  },
  {
    productId: "prod-002",
    productName: "Industrial Widget B",
    currentMonth: 50,
    nextMonth: 45,
    trend: "down",
  },
  {
    productId: "prod-003",
    productName: "Component Alpha",
    currentMonth: 150,
    nextMonth: 180,
    trend: "up",
  },
];

// Mock Historical Sales
export const mockHistoricalSales = [
  { month: "Jul 2024", revenue: 125000, orders: 45, avgOrderValue: 2778 },
  { month: "Aug 2024", revenue: 138000, orders: 52, avgOrderValue: 2654 },
  { month: "Sep 2024", revenue: 142000, orders: 48, avgOrderValue: 2958 },
  { month: "Oct 2024", revenue: 156000, orders: 55, avgOrderValue: 2836 },
  { month: "Nov 2024", revenue: 168000, orders: 62, avgOrderValue: 2710 },
  { month: "Dec 2024", revenue: 185000, orders: 68, avgOrderValue: 2721 },
];

// Demo Login Credentials
export const DEMO_CREDENTIALS = {
  username: "admin",
  password: "demo123",
};

// Mock Invoices Full (with invoiceType)
export const mockInvoicesFull = [
  {
    id: "inv-001",
    companyId: "comp-002",
    invoiceNumber: "INV-2024-001",
    invoiceType: "customer",
    salesOrderId: "so-001",
    customerId: "cust-001",
    customerName: "PT. Maju Sejahtera",
    invoiceDate: "2024-01-15",
    dueDate: "2024-02-15",
    status: "paid",
    subtotal: 15000000,
    taxAmount: 1650000,
    total: 16650000,
    amountPaid: 16650000,
    amountDue: 0,
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "inv-002",
    companyId: "comp-002",
    invoiceNumber: "INV-2024-002",
    invoiceType: "customer",
    salesOrderId: "so-002",
    customerId: "cust-002",
    customerName: "CV. Sukses Mandiri",
    invoiceDate: "2024-01-20",
    dueDate: "2024-02-20",
    status: "partial",
    subtotal: 25000000,
    taxAmount: 2750000,
    total: 27750000,
    amountPaid: 15000000,
    amountDue: 12750000,
    createdAt: new Date("2024-01-20"),
  },
  {
    id: "inv-003",
    companyId: "comp-002",
    invoiceNumber: "INV-2024-003",
    invoiceType: "customer",
    salesOrderId: "so-003",
    customerId: "cust-003",
    customerName: "PT. Bersama Jaya",
    invoiceDate: "2024-01-25",
    dueDate: "2024-02-25",
    status: "unpaid",
    subtotal: 8500000,
    taxAmount: 935000,
    total: 9435000,
    amountPaid: 0,
    amountDue: 9435000,
    createdAt: new Date("2024-01-25"),
  },
];

// Mock Customers Full
export const mockCustomersFull = [
  {
    id: "cust-001",
    companyId: "comp-002",
    code: "CUST-001",
    name: "PT. Maju Sejahtera",
    email: "info@majusejahtera.co.id",
    phone: "+62 21 5551234",
    address: "Jl. Sudirman No. 123",
    city: "Jakarta",
    state: "DKI Jakarta",
    country: "ID",
    postalCode: "10110",
    creditLimit: 100000000,
    paymentTerms: 30,
    isActive: true,
    createdAt: new Date("2023-06-15"),
  },
  {
    id: "cust-002",
    companyId: "comp-002",
    code: "CUST-002",
    name: "CV. Sukses Mandiri",
    email: "contact@suksesmandiri.co.id",
    phone: "+62 22 5552345",
    address: "Jl. Asia Afrika No. 45",
    city: "Bandung",
    state: "Jawa Barat",
    country: "ID",
    postalCode: "40112",
    creditLimit: 50000000,
    paymentTerms: 14,
    isActive: true,
    createdAt: new Date("2023-07-20"),
  },
  {
    id: "cust-003",
    companyId: "comp-002",
    code: "CUST-003",
    name: "PT. Bersama Jaya",
    email: "sales@bersamajaya.co.id",
    phone: "+62 31 5553456",
    address: "Jl. Pemuda No. 78",
    city: "Surabaya",
    state: "Jawa Timur",
    country: "ID",
    postalCode: "60271",
    creditLimit: 75000000,
    paymentTerms: 30,
    isActive: true,
    createdAt: new Date("2023-08-10"),
  },
];
